<?php

/**
 * @file
 * Contains aweber_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function aweber_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the aweber_block module.
    case 'help.page.aweber_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integrates Drupal 8 with The Aweber Platform.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function aweber_block_theme() {
  return [
    'aweber_block' => [
      'variables' => ['variable' => NULL],
    ],
  ];
}
